config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  resources :articles, except: [:destroy]

  resources :books, only: [:index] do
    get 'search', on: :collection
  end

  resources :articles_users, only: [:create, :destroy]
  resources :books_users, only: [:create, :update, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :articles_users
  has_many :users, through: :articles_users

  validates :title, :url, presence: true
  validates :url, uniqueness: true
  validates :url, format: URI::regexp(%w(http https))
  validates :kid_friendly, inclusion: { in: [true, false] }
  validates :approved, inclusion: { in: [true, false] }

  # def self.search(search)
  #   find(:all, :conditions => ['tags LIKE ?', "%#{search}%"]
  # end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize_user, except: [:index]

  def index
    if params[:search]
      @articles = ArticlesUser.includes(:article).where("tags ILIKE ?", "%#{params[:search]}%").references(:articles).where(articles_users: { access: "public" }).order(created_at: :desc)
      if @articles.blank?
        @empty_msg_articles = "Sorry! No matches found for the tags #{params[:search]}."
      else
        @articles = @articles.uniq(&:article_id)
      end
      @search_msg = params[:search]

    else
      if current_user
        @user = User.find(current_user.id)
      end
      #if current_user clicks 'Browse articles book,arked by others'
      if (current_user && params[:show_available])
        # remove the bookmarks that are saved by the current user and may or may not be saved by others.
        @articles = ArticlesUser.includes(:article).where.not(articles_users: { user_id: @user.id }).where(articles_users: { access: "public" }).order(created_at: :desc)
        if @articles.blank?
          @empty_msg_articles = "Sorry! No article-bookmarks available in public domain yet!"
        else
          @articles = @articles.uniq(&:article_id)
          # remove the bookmarks that are saved by others as well as current_user
          sql = "select article_id from articles_users where article_id in (select article_id  from articles_users group by article_id having count(*) > 1) and user_id = #{current_user.id}"
          @articles_to_exclude = ActiveRecord::Base.connection.exec_query(sql)
          if @articles_to_exclude.length == @articles.length
            @empty_msg_articles = "Sorry! No article-bookmarks available in public domain yet!"
          end
        end
        @msg_access = "show public access"

      elsif current_user
        @articles = ArticlesUser.includes(:article).where(articles_users: { user_id: @user.id }).order(created_at: :desc)
        if @articles.blank?
          @empty_msg_articles = "You have not bookmarked any article yet! Please click the links (+) above to create bookmarks"
        else
          @msg_access = "show private access"
        end

      elsif !user_signed_in?
        @articles = ArticlesUser.includes(:article).where(articles_users: { access: "public" }).order(created_at: :desc)

        if @articles.blank?
          @empty_msg_articles = "Sorry! No article-bookmarks available in public domain."
        else
          @articles = @articles.uniq(&:article_id)
        end
      end
   end
   @ratings_collection = ArticlesUser::RATINGS
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(current_user.id)
    @articles_user = ArticlesUser.where("article_id = ? and user_id = ?", @article.id, @user.id).first
    @ratings_collection = ArticlesUser::RATINGS
  end

  def new
    @article = Article.new
    @articles_user = ArticlesUser.new
    @ratings_collection = ArticlesUser::RATINGS
  end

  def edit
    @user = User.find(current_user.id)
    @article = Article.find(params[:id])
    @articles_user = ArticlesUser.where("article_id = ? and user_id = ?", @article.id, @user.id).first
    @ratings_collection = ArticlesUser::RATINGS
  end

  def create
    @user = User.find(current_user.id)
    @article = Article.new(articles_params)

    host = URI.parse(params[:article][:url]).host
    if !host.nil?
      @article.host = host.start_with?('www.') ? host[4..-1] : host
    end
    @article.shared_by = @user.id
    @ratings_collection = ArticlesUser::RATINGS
    @articles_user = ArticlesUser.new(articles_users_params)

    if @article.save
      @articles_user.user = @user
      @articles_user.article = @article
      if @articles_user.save
        redirect_to @article, notice: 'Bookmark was successfully added.'
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def update
    @ratings_collection = ArticlesUser::RATINGS
    @user = User.find(current_user.id)
    @article = Article.find(params[:id])

    host = URI.parse(params[:article][:url]).host
    if !host.nil?
      @article.host = host.start_with?('www.') ? host[4..-1] : host
    end

    @articles_user = ArticlesUser.where("article_id = ? and user_id = ?", @article.id, @user.id).first
    if @article.update(articles_params) && @articles_user.update(articles_users_params)
      redirect_to @article, notice: 'Bookmark was updated successfully.'
    else
      render 'edit'
    end
  end

  private
    def articles_params
      params.require(:article).permit(:title, :url, :tags)
    end

    def articles_users_params
      params.require(:articles_user).permit(:user_rating, :access, :status)
    end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Sign in required before proceeding."
      redirect_to new_user_session_path
    end
  end
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="grid-x grid-padding-x">
    <div class="small-1 large-1 cell"></div>
    <div class="small-11 large-10 cell">
      <% if @article.persisted? %>
        <h4 class="page-heading">Edit Article Bookmark</h4>
      <% else %>
        <h4 class="page-heading">Add Article Bookmark</h4>
      <% end %>
      <p></p>
      <%= render "layouts/errors", object: @article %>
      <%= render "layouts/errors", object: @articles_user %>
    </div>
    <div class="large-1 cell"></div>

    <div class="small-1 large-1 cell">
      <%= f.label :title, class: "text-right middle" %>
    </div>
    <div class="small-11 large-10 cell">
      <%= f.text_field :title %>
    </div>
    <div class="large-1 cell"></div>

    <div class="small-1 large-1 cell">
      <%= f.label :url, "Url", class: "text-right middle" %>
    </div>
    <div class="small-11 large-10 cell">
      <%= f.text_field :url %>
    </div>
    <div class="large-1 cell"></div>


    <%= fields_for :articles_user do |articles_user_fields| %>
      <div class="small-1 large-1 cell"> </div>
      <div class="small-11 large-10 cell">
        <%= articles_user_fields.check_box :access, {}, "private", "public" %>
        <%= articles_user_fields.label :access, "Private" %>
        <%= articles_user_fields.check_box :status, {}, "To-do", "read" %>
        <%= articles_user_fields.label :status, "To-do" %>
      </div>
      <div class="large-1 cell"></div>

      <div class="small-1 large-1 cell">
        <%= articles_user_fields.label :user_rating, "Rating:", class: "text-right" %>
      </div>
      <div class="small-11 large-10 cell">
        <% @ratings_collection.each do |ratings_array| %>
          <%= articles_user_fields.radio_button :user_rating, ratings_array.first %>
          <%= articles_user_fields.label :user_rating, "#{ratings_array.last}", value: "#{ratings_array.first}" %>
        <% end %>
      </div>
      <div class="large-1 cell"></div>
    <% end %>

    <div class="small-1 large-1 cell">
      <%= f.label :tags, class: "text-right middle" %>
    </div>
    <div class="small-11 large-10 cell">
      <%= f.text_field :tags %>
    </div>
    <div class="large-1 cell"></div>

    <div class="small-1 large-1 cell"> </div>
    <div class="small-11 large-10 cell">
      <%= f.submit @article.persisted? ? "Update Bookmark" : "Add Bookmark", class: "button secondary " %>
    </div>
    <div class="large-1 cell"></div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

app/views/articles/index.html.erb
<% if !@search_msg.nil? %>
  <h4 class="page-heading">Article Bookmarks</span></h4>

  <p class="heading-link">
    <%= link_to "Browse articles bookmarked by others", articles_path(show_available: "Show Available") %>
  </p>
  <br>
  <span class="heading-tags"> Search Results for Tag: '<%= @search_msg %>', <%= @articles.count %> found. </span>
  <br>
  <span class="heading-tags">Please note: Only the bookmarks available in public domain will be shown here.</span>
<% else %>
  <% if !user_signed_in? || @msg_access == "show public access"%>
    <h5 class="page-heading">Articles bookmarked by other Users</h5>
  <% else %>
    <h4 class="page-heading">My Article Bookmarks</h4>
    <p class="heading-link">
      <%= link_to "Browse articles bookmarked by others", articles_path(show_available: "Show Available") %>
    </p>
  <% end %>
<% end %>
<hr>
<% if !@empty_msg_articles.nil? %>
  <p class="empty_message"><%= @empty_msg_articles %></p>
<% else %>
  <!-- This logic is to remove the bookmarks that the current_user as well as other users have already saved. -->
  <% remove_articles = [] %>
  <% if current_user && !@articles_to_exclude.nil? %>
    <% @articles_to_exclude.each do |row| %>
      <% remove_articles << row["article_id"] %>
    <% end %>
  <% end %>

  <% @articles.each do |item| %>
    <% next if current_user && remove_articles.include?(item.article_id) %>

    <% if (@msg_access == "show private access" && item.access == "private") %>
      <span data-tooltip tabindex="1" title="Private Bookmark"><i class="fi-lock icon-lock-style" aria-hidden="true"></i></span>
    <% end %>
    <%= link_to "#{item.article.title}", item.article.url, class: "item" %><br>
    <span class="item-DT">Saved from:</span>
    <span class="item-DD"><%= item.article.host %></span>
    <span class="item-DT"> on: </span><span class="item-DD-small"><%= item.created_at.time.to_date %></span><br>
    <span class="item-DT">Tags: </span><%= link_to item.article.tags, articles_path(search: item.article.tags), class: "tags-link" %>
    &emsp;

    <% if !item.user_rating.nil? %>
      <span class="item-DT"> Rating:</span>
      <span class="item-DD-small"><%= @ratings_collection.assoc(item.user_rating)[1] %></span>
    <% end %>
    &emsp;
    <% if current_user && current_user.id == item.user_id %>
      <span class="item-DT"> Status:</span>
      <span class="item-DD-small"><%= item.status %></span><br>
      <%= link_to "Edit", edit_article_path(item.article), class: "hollow button secondary small btn-action" %>

      <%= link_to 'Delete', articles_user_path(item),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },  class: "hollow button secondary small btn-action" %>
    <% end %>

    <% if (current_user && current_user.id != item.user_id) || !user_signed_in? %>
      <br>
      <%= button_to 'Save', articles_users_path, method: :post, params: { article_user_data: item }, name: "save", class: "hollow button secondary small btn-action" %>
      <%= button_to 'Save in To-dos', articles_users_path, method: :post, params: { article_user_data: item }, name: "save_to_do", class: "hollow button secondary small btn-action" %>
    <% end %>

    <hr>
  <% end %>
<% end %>

app/views/articles/new.html.erb
<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

app/views/articles/show.html.erb
<h4>Article Bookmark Details:</h4>
<hr>
<% if current_user %>

  <% if (@articles_user.access == "private") %>
    <span data-tooltip tabindex="1" title="Private Bookmark"><i class="fi-lock icon-lock-style" aria-hidden="true"></i></span>
  <% end %>
  <%= link_to "#{@article.title}", @article.url, class: "item" %><br>
  <span class="item-DT">Url: </span>
  <span class="item-DD"><%= link_to @article.url, @article.url, class: "item" %></span><br>
  <span class="item-DT">Saved from:</span>
  <span class="item-DD"><%= @article.host %></span>
  <span class="item-DT"> on: </span><span class="item-DD"><%= @article.updated_at.time.to_date %></span><br>
  <span class="item-DT">Tags: </span>
  <span class="item-DD"><%= link_to @article.tags, articles_path(search: @article.tags), class: "tags-link" %></span>
  <br>
  <span class="item-DT"> Access:</span>
  <span class="item-DD-small"><%= @articles_user.access %></span>
  <br>

  <% if !@articles_user.user_rating.nil? %>
    <span class="item-DT"> Rating:</span>
    <span class="item-DD-small"><%= @ratings_collection.assoc(@articles_user.user_rating)[1] %></span>
  <% end %>
  <br>
  <span class="item-DT"> Status:</span>
  <span class="item-DD-small"><%= @articles_user.status %></span>
  <p></p>
  <%= link_to "Edit", edit_article_path(@article), class: "hollow button secondary small btn-action" %>
  &emsp;
  <%= link_to 'Delete', article_path(@article),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "hollow button secondary small btn-action" %>

  &emsp;
  <%= link_to "Back to Article Bookmarks", articles_path, class: "hollow button secondary small btn-action" %>
<% end %>