config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  resources :articles, except: [:destroy]

  resources :books, only: [:index] do
    get 'search', on: :collection
  end

  resources :articles_users, only: [:create, :destroy]
  resources :books_users, only: [:create, :update, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :books_users
  has_many :users, through: :books_users

  validates :title, :isbn_13, :publisher, :published_at, presence: true
  validates :isbn_13, uniqueness: true
  validates :kid_friendly, inclusion: { in: [true, false] }
  validates :approved, inclusion: { in: [true, false] }

  after_validation :log_errors, :if => Proc.new {|m| m.errors}

  def log_errors
    Rails.logger.debug self.errors.full_messages.join("\n")
  end

  def self.save_data_from_api(search)
    response = HTTParty.get('https://www.googleapis.com/books/v1/volumes?q=' + search)

    books = []
    if !response.nil?
      response["items"].each do |item|
        #if isbn info not avalable, then don't save the book. isbn_13 is a uniq field and helps to avoid duplicate data.
        isbn_data = item["volumeInfo"]["industryIdentifiers"]
        next if isbn_data.nil?

        book = Book.new
        book.isbn_13 = isbn_data[0]["identifier"]
        book.title = item["volumeInfo"]["title"]

        if !item["volumeInfo"]["authors"].nil?
          book.authors = item["volumeInfo"]["authors"].join(", ")
        end

        if !item["searchInfo"].nil?
          book.description = item["searchInfo"]["textSnippet"]
        else
          book.description = "N/A"
        end

        book.publisher = item["volumeInfo"]["publisher"]

        if !item["volumeInfo"]["publishedDate"].nil?
          book.published_at = item["volumeInfo"]["publishedDate"][0..3].to_i
        else
          book.published_at = 0
        end

        if !item["volumeInfo"]["categories"].nil?
          book.categories = item["volumeInfo"]["categories"][0]
        end

        book.googlebooks_rating = item["volumeInfo"]["averageRating"]

        if !item["volumeInfo"]["imageLinks"].nil?
          book.thumbnail_url = item["volumeInfo"]["imageLinks"]["smallThumbnail"]
        end

        if book.save
          books << book
        end
      end
    else
      puts "API response Nil"
    end
    books
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if current_user
      @user = User.find(current_user.id)
    end
    @ratings_collection = BooksUser::RATINGS

    if (current_user && params[:show_available])
      # remove the bookmarks that are saved by the current user and may or may not be saved by others.
      @books =BooksUser.includes(:book).where.not(books_users: { user_id: @user.id }).order(created_at: :desc)
      if @books.blank?
        @empty_msg_books = "Sorry! No User has bookmarked any book yet! Be the first to bookmark a book."
      else
        @books = @books.uniq(&:book_id)
        # remove the bookmarks that are saved by current_user as well as others
        sql = "select book_id from books_users where book_id in (select book_id  from books_users group by book_id having count(*) > 1) and user_id = #{current_user.id}"
        @books_to_exclude = ActiveRecord::Base.connection.exec_query(sql)
        if @books_to_exclude.count == @books.count
          @empty_msg_books = "Sorry! No User has bookmarked any book yet! Be the first to bookmark a book."
        end
      end

    elsif current_user
      @books = BooksUser.includes(:book).where(books_users: { user_id: @user.id }).order(created_at: :desc)
      if @books.blank?
        @empty_msg_books = "You have not bookmarked any books yet! Please click the links (+) above to create bookmarks."
      end
    elsif !user_signed_in?
      @books = BooksUser.includes(:book).order(created_at: :desc)
      if @books.blank?
        @empty_msg_books = "None has bookmarked any books yet!. Please go to the books section to search a book."
      else
        @books = @books.uniq(&:book_id)
      end
    end
  end

  def search
    if params[:book_search]
      if current_user
        @books = Book.where("title ILIKE ? OR authors ILIKE ? OR description ILIKE ?", "%#{params[:book_search]}%", "%#{params[:book_search]}%", "%#{params[:book_search]}%").where("id NOT IN(select book_id from books_users where user_id = ?)", current_user.id)
        # @books = Book.joins(:books_users).where.not(books_users: { user_id: current_user.id }).where("title ILIKE ? OR authors ILIKE ? OR description ILIKE ?", "%#{params[:book_search]}%", "%#{params[:book_search]}%", "%#{params[:book_search]}%")
      else
        @books = Book.where("title ILIKE ? OR authors ILIKE ? OR description ILIKE ?", "%#{params[:book_search]}%", "%#{params[:book_search]}%", "%#{params[:book_search]}%")
      end
      @search_query = params[:book_search]
    elsif params[:book_category_search]
      if current_user
        # @books = Book.joins(:books_users).where.not(books_users: { user_id: current_user.id }).where("categories ILIKE ?", "%#{params[:book_category_search]}%")
        @books = Book.where("categories ILIKE ?", "%#{params[:book_category_search]}%").where("id NOT IN(select book_id from books_users where user_id = ?)", current_user.id)
      else
        @books = Book.where("categories ILIKE ?", "%#{params[:book_category_search]}%")
      end
      @search_query = params[:book_category_search]
    end

    if (params[:book_search] || params[:book_category_search]) && @books.blank?
      @empty_msg_books = "Sorry! no results matched your query."
    end
  end
end

app/views/books/_change_rating_form.html.erb
<div id="change-rating-div<%= item.id %>">
  <span class="item-DD-small"><strong>User Rating: </strong>
    <% if !item.user_rating.nil? %>
      <%= @ratings_collection.assoc(item.user_rating)[1] %>
      <% else %>
      None
    <% end %>
  </span>
  <button class="hollow button secondary small btn-action" type="button" data-toggle="change-rating-dropdown<%= item.id %>" >Change User Rating</button>
  <div class="dropdown-pane" data-position="bottom" data-alignment="center" id="change-rating-dropdown<%= item.id %>" data-dropdown data-auto-focus="true">
    <%= form_with model: BooksUser.find(item.id), data: {'js-change-rating-form' => true} do |f| %>
      <div class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="cell medium-12">
            <% @ratings_collection.each do |ratings_array| %>
              <%= f.radio_button :user_rating, ratings_array.first %>
              <%= f.label :user_rating, "#{ratings_array.last}", value: "#{ratings_array.first}" %>
            <% end %>
          </div>
          <div class="cell medium-12">
              <%= f.submit "Submit", name: "change_rating", class: "button tiny secondary change-status-btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/_change_status_form.html.erb
<div id="change-status-div<%= item.id %>">
  <span class="item-DD-small"><strong>Status: </strong><%= item.status %></span>
  <button class="hollow button secondary small btn-action" type="button" data-toggle="change-status-dropdown<%= item.id %>" >Change Status</button>
  <div class="dropdown-pane" data-position="bottom" data-alignment="center" id="change-status-dropdown<%= item.id %>" data-dropdown data-auto-focus="true">
    <%= form_with model: BooksUser.find(item.id), data: {'js-change-status-form' => true} do |f| %>
      <div class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="cell medium-12">
              <%= f.radio_button :status, "read" %>
              <%= f.label :status, "read", value: "read" %>
              <%= f.radio_button :status, "To-do" %>
              <%= f.label :status, "To-do", value: "To-do" %>
          </div>
          <div class="cell medium-12">
              <%= f.submit "Submit", name: "change_status", id: "change-status-btn#{item.id}", class: "button tiny secondary change-status-btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/_search_book_form.html.erb
<p class="page-heading" >Search Book</p>
<form action="<%= search_books_url %>" method="get" id="book-search-form">
  <%= text_field_tag :book_search, params[:book_search], placeholder: "Enter keyword (title, descrption, author)", class: "search-input" %>
  <%= submit_tag "Search Books", name: nil, class: "button secondary " %>
</form>

app/views/books/destroy.js.erb
$("#delete-div<%= item %>").remove();

app/views/books/index.html.erb
<%= render "search_book_form" %>
<hr >
<% if !user_signed_in? %>
  <h5 class="page-heading">Books bookmarked by other Users</h5>
<% else %>
  <h5 class="page-heading">My Book Bookmarks</h5>
  <p class="heading-link">
    <%= link_to "Browse Books bookmarked by others", books_path(show_available: "Show Available") %>
  </p>
<% end %>
<p></p>
<% if !@empty_msg_books.nil? %>
  <p class="empty_message"><%= @empty_msg_books %></p>
<% else %>
  <% remove_books = [] %>
  <% if current_user && !@books_to_exclude.nil? %>
    <% @books_to_exclude.each do |row| %>
      <% remove_books << row["book_id"] %>
    <% end %>
  <% end %>

  <% @books.each do |item| %>
    <% next if current_user && remove_books.include?(item.book_id) %>
    <div id="delete-div<%= item.id %>" >
      <div class="grid-x grid-margin-x">
        <%= render partial: "layouts/book", object: item.book %>
            <% if (current_user && current_user.id == item.user_id) %>
              <div class="grid-x grid-margin-x">
                <div class="small-12 large-4 cell">
                  <%= render partial: "change_status_form", locals: {item: item} %>
                </div>
                <div class="small-12 large-8 cell">
                  <%= render partial: "change_rating_form", locals: {item: item} %>
                </div>
              </div>
              <p>
                <%= link_to 'Delete Bookmark', books_user_path(item), remote: true,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },  class: "hollow button secondary small btn-action" %>
              </p>
            <% elsif (current_user && current_user.id != item.user_id) || !user_signed_in? %>
              <br>
              <%= button_to 'Save', books_users_path, method: :post, params: { book_data: item.book }, name: "save", class: "hollow button secondary small btn-action" %>
              <%= button_to 'Save in To-dos', books_users_path, method: :post, params: { book_data: item.book }, name: "save_to_do", class: "hollow button secondary small btn-action" %>
            <% end %>
          </div> <!-- closing div for partial -->
        <div class="small-12 large-12 cell "><hr></div>
      </div>
    </div> <!-- delete-div -->
  <% end %>
<% end %>

app/views/books/search.html.erb
<%= render "search_book_form" %>

<% if @empty_msg_books %>
  <p class="subheader"><%= @empty_msg_books %></p>
<% else %>
  <!-- This condition required for the same page is rendering form as well as results of form submission. -->
  <% if !@books.blank? %>
    <p class="subheader">Search Results for Books: <em>'<%= @search_query %>'</em>, Total: <%= @books.count %> found.</p>
    <br>
    <% @books.each do |book| %>
      <div id="delete-div<%= book.id %>" >
        <div class="grid-x grid-margin-x">
            <%= render partial: "layouts/book", object: book %>
            <br>
            <%= button_to 'Save', books_users_path, method: :post, params: { book_data: book }, name: "save", class: "hollow button secondary small btn-action" %>
            <%= button_to 'Save in To-dos', books_users_path, method: :post, params: { book_data: book }, name: "save_to_do", class: "hollow button secondary small btn-action" %>
          </div> <!-- closing div for partial -->
          <div class="small-12 large-12 cell "><hr></div>
        </div>
      </div> <!-- delete-div -->
    <% end %>
  <% end %>
<% end %>