config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  resources :articles, except: [:destroy]

  resources :books, only: [:index] do
    get 'search', on: :collection
  end

  resources :articles_users, only: [:create, :destroy]
  resources :books_users, only: [:create, :update, :destroy]
end

app/views/layouts/_book.html.erb
<div class="small-2 large-2 cell">
  <img src="<%= book.thumbnail_url %>" class="book-thumbnail">
</div>
<div class="small-10 large-10 cell ">
  <span class="item-DD-bold"><%= book.title %></span>
  <span class="item-DT"> by </span>
  <span class="item-DD-purple"><%= book.authors %></span>
  <span class="item-DT"> (<%= book.published_at %>) </span>

  <div class="grid-x grid-margin-x">
    <div class="small-12 large-4 cell">
      <span class="item-DD-small">Category: <%= book.categories %></span>
    </div>
    <div class="small-12 large-8 cell">
      <% if !book.googlebooks_rating.nil? %>
        <span class="item-DD-small">Google-books rating: <%= book.googlebooks_rating %></span>
      <% end %>
    </div>
  </div>
  <span class="item-DT"><%= book.description %></span>

app/views/layouts/_books_user.html.erb
<div id="change-status-div<%= book.id %>">

<span class="item-DD-small"><strong>Status: </strong><%= book.status %></span>
        <button class="hollow button secondary small btn-action" type="button" data-toggle="change-status-dropdown<%= book.id %>" >Change Status</button>
        <div class="dropdown-pane" data-position="bottom" data-alignment="center" id="change-status-dropdown<%= book.id %>" data-dropdown data-auto-focus="true">

          <%= form_with model: BooksUser.find(book.id), data: {'js-change-status-form' => true} do |f| %>
            <div class="grid-container">
              <div class="grid-x grid-margin-x">
                <div class="cell medium-12">
                    <%= f.radio_button :status, "read" %>
                    <%= f.label :status, "read", value: "read" %>
                    <%= f.radio_button :status, "To-do" %>
                    <%= f.label :status, "To-do", value: "To-do" %>
                </div>
                <div class="cell medium-12">
                    <%= f.submit "Submit", name: "change_status", id: "change-status-btn#{book.id}", class: "button tiny secondary change-status-btn" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

    </div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <span>Please enter valid information:</span>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MyMarker!" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <%= link_to root_path, class: "home" do %>
          <i class="fi-bookmark"></i>
          MyMarker!
        <% end %>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <%- if current_user -%>
            <li class="menu-text">Welcome <%= current_user.first_name %>!</li>
            <li><%= link_to 'Update Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </div>
    </div>

    <div class="callout large primary">
      <div class="row column text-center">
        <h3 class="site-title"><i class="fi-bookmark"></i> MyMarker! - Bookmarking App <i class="fi-bookmark"></i></h3>
        <h4 class="subheader">Create and save Bookmarks (Articles and Books) quickly!</h4>
        <h5 class="subheader">View recently Bookmarked items by clciking the links below!</h5>
        <p></p>
        <%- if current_user -%>
          <div class="button-group" id="main-menu">
            <%= link_to "My Article Bookmarks", articles_path, class: "button custom" %>
            <%= link_to '<i class="fi-plus" aria-hidden="true"></i>'.html_safe, new_article_path, title: "Add Article", class: "button arrow-only custom add-article" %>
          </div>
          <div class="button-group">
            <%= link_to "My Book Bookmarks", books_path, class: "button custom" %>
            <%= link_to '<i class="fi-plus" aria-hidden="true"></i>'.html_safe, search_books_path, title: "Add Book", class: "button arrow-only custom" %>
          </div>
        <%- else %>
          <%= link_to "Articles", articles_path, class: "button custom" %>
          <%= link_to "Books", books_path, class: "button custom" %>
        <%- end -%>
      </div>
    </div>

    <div class="grid-container">
      <div class="grid-x grid-margin-x" id="content">
        <div class="medium-9 cell bookmarks-data" >
        <%- flash.each do |key, value| -%>
        <div class="callout small flash-msg alert flash flash-<%= key %>">
          <%= value %>
        </div>
        <%- end -%>

          <%= yield %>
        </div>
        <div class="medium-3 cell" data-sticky-container>
          <div class="sticky" data-sticky data-anchor="content">
            <h5>Articles-Tags</h5>
            <ul class="custom-menu">
              <li><%= link_to "Ruby", articles_path(search: "Ruby"), class: "tags-link" %></li>
              <li><%= link_to "Rails", articles_path(search: "Rails"), class: "tags-link" %></li>
              <li><%= link_to "JavaScript", articles_path(search: "JavaScript"), class: "tags-link" %></li>
              <li><%= link_to "REST API", articles_path(search: "REST API"), class: "tags-link" %>
              <li><%= link_to "Framework", articles_path(search: "Framework"), class: "tags-link" %></li>
            </ul>

            <h5>Books-Categories</h5>
            <ul class="custom-menu">
              <li><%= link_to "Computers", search_books_path(book_category_search: "Computers"), class: "tags-link" %></li>
              <li><%= link_to "Business & Economics", search_books_path(book_category_search: "Business & Economics"), class: "tags-link" %></li>
              <li><%= link_to "Health & Fitness", search_books_path(book_category_search: "Health & Fitness"), class: "tags-link" %></li>
              <li><%= link_to "Photography", search_books_path(book_category_search: "Photography"), class: "tags-link" %></li>
              <li><%= link_to "Self-Help", search_books_path(book_category_search: "Self-Help"), class: "tags-link" %></li>
              <li><%= link_to "Travel", search_books_path(book_category_search: "Travel"), class: "tags-link" %></li>
              <li><%= link_to "Fiction", search_books_path(book_category_search: "Fiction"), class: "tags-link" %></li>
              <li><%= link_to "Biography", search_books_path(book_category_search: "Biography"), class: "tags-link" %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
      <p><br /><br /></p>
    <footer>
      <div class="grid-x">
        <div class="medium-6 cell">
          <ul class="menu custom-menu">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </div>

        <div class="medium-6 cell">
          <ul class="menu align-right">
            <li class="menu-text">© 2018 MyBookmarks</li>
          </ul>
        </div>
      </div>
    </footer>

  </body>
</html>